---
- hosts: all
  become: yes
  tasks:
   - name: Add Docker GPG apt Key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add Docker Repository
     apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu focal stable
       state: present

   - name: install Docker
     apt:
       name: 
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-buildx-plugin
       - docker-compose-plugin
       state: present
       update_cache: true
   - name: changing Docker to systemd driver
     copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }
   - name: Restart docker
     service:
       name: docker
       state: restarted
       enabled: true
   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     apt:
       name: kubelet #=1.22.4-00
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm #=1.22.4-00
       state: present
   - name: BUG
     file: 
       path: /etc/containerd/config.toml
       state: absent
   - name: Restart containerd
     service:
       name: containerd
       state: restarted
       
- hosts: control_plane
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl #=1.22.4-00
       state: present
       force: yes